# Test your FastAPI endpoints

GET http://127.0.0.1:8000
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

GET http://127.0.0.1:8000/goodbye/User
Accept: application/json

GET http://127.0.0.1:8000/protein/User
Accept: application/json

GET http://127.0.0.1:8000/radius/User
Accept: application/json